/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'project' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "at32f435_437.h"

/* ArteryTek::Device:at32f435_437_firmware_library:crm@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_CRM
/* ArteryTek::Device:at32f435_437_firmware_library:exint@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_EXINT
/* ArteryTek::Device:at32f435_437_firmware_library:gpio@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_GPIO
/* ArteryTek::Device:at32f435_437_firmware_library:misc@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_MISC
/* ArteryTek::Device:at32f435_437_firmware_library:scfg@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_SCFG
/* ArteryTek::Device:at32f435_437_firmware_library:usart@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_USART


#endif /* RTE_COMPONENTS_H */
